### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Keyword.get/3

### ISSUE THREAD

**Issue by hukendo** [claytongentry/furlex#20]
```
iex(1)> Furlex.unfurl("https://www.youtube.com/watch?v=Gh6H7Md_L2k")

12:21:41.019 [error] Task #PID<0.683.0> started from #PID<0.680.0> terminating
** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:191: Keyword.get(nil, :oembed_host, nil)
    (furlex) lib/furlex/oembed.ex:112: Furlex.Oembed.process_url/1
    (furlex) lib/furlex/oembed.ex:7: Furlex.Oembed.request/5
    (furlex) lib/furlex/oembed.ex:20: Furlex.Oembed.fetch_providers/1
    (furlex) lib/furlex/oembed.ex:67: Furlex.Oembed.provider_from_url/2
    (furlex) lib/furlex/oembed.ex:53: Furlex.Oembed.endpoint_from_url/3
    (furlex) lib/furlex/fetcher.ex:26: Furlex.Fetcher.fetch_oembed/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Furlex.Fetcher.fetch_oembed/2
    Args: ["https://www.youtube.com/watch?v=Gh6H7Md_L2k", []]
** (EXIT from #PID<0.680.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.get/3
        (elixir) lib/keyword.ex:191: Keyword.get(nil, :oembed_host, nil)
        (furlex) lib/furlex/oembed.ex:112: Furlex.Oembed.process_url/1
        (furlex) lib/furlex/oembed.ex:7: Furlex.Oembed.request/5
        (furlex) lib/furlex/oembed.ex:20: Furlex.Oembed.fetch_providers/1
        (furlex) lib/furlex/oembed.ex:67: Furlex.Oembed.provider_from_url/2
        (furlex) lib/furlex/oembed.ex:53: Furlex.Oembed.endpoint_from_url/3
        (furlex) lib/furlex/fetcher.ex:26: Furlex.Fetcher.fetch_oembed/2
        (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
```

**Comment by abitdodgy** [comment]
You need to configure the oembed host in `config.exs`. This should be clarified in the read me.

```elixir
config :furlex, Furlex.Oembed,
  oembed_host: "https://oembed.com"
```

**Comment by claytongentry** [comment]
Thanks!

**Comment by claytongentry** [comment]
@hukendo please give [v.0.4.2](https://hex.pm/packages/furlex/0.4.2) a shot
