### ISSUE TITLE
Won't start on Phoenix 1.3 Elixir 1.5.2

### ISSUE THREAD

**Issue by abitdodgy** [claytongentry/furlex#4]
I'm getting this error when I try to start Phoenix after installing Furlex. I haven't tested it on other versions of Elixir.

```
** (Mix) Could not start application furlex: Furlex.start(:normal, []) returned an error: shutdown: failed to start child: Furlex.Oembed
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:invalid, "<", 0}}
            (furlex) lib/furlex/oembed.ex:21: Furlex.Oembed.fetch_providers/1
            (furlex) lib/furlex/oembed.ex:114: Furlex.Oembed.init/1
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by claytongentry** [comment]
Thanks for the PR! I've tested with your change on phoenix 1.3 and elixir 1.5, this looks good to me now.
